[toolchain]
package_manager = "yarn"
solana_version = "1.18.26"

[features]
seeds = false
skip-lint = false

[programs.devnet]
nft_staking = "FXtW7PAK8KtFKBsBiyFMK2BrrU8dt9gHPzoVrBDNkWgf"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/home/kartik/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
