[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
nft_staking = "4BGAeWBHxqo3yGiGgViGQaCkXA9Xbb5HQzn4oAKf2U1V"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/kartik/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
